# Generated by Django 6.0.1 on 2026-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('muallif', models.CharField(max_length=100)),
                ('nashr_yili', models.IntegerField()),
                ('kitob_turi', models.CharField(default="Noma'lum", max_length=100)),
                ('kitob_linki', models.TextField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='kitoblar/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kitob_images/')),
            ],
        ),
    ]
