# Generated by Django 6.0.1 on 2026-01-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
