# Generated by Django 6.0.1 on 2026-01-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0002_alter_kitob_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/files'),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kitoblar/'),
        ),
    ]
