# Generated by Django 6.0.1 on 2026-01-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0003_alter_kitob_file_alter_kitob_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/kitoblar/'),
        ),
    ]
