# Generated by Django 6.0.1 on 2026-01-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0004_alter_kitob_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kitoblar/'),
        ),
    ]
