# Generated by Django 6.0.1 on 2026-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0006_alter_kitob_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='narxi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
