# Generated by Django 6.0.1 on 2026-01-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0007_kitob_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitob',
            name='is_favorite',
        ),
    ]
