# Generated by Django 6.0.1 on 2026-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0008_remove_kitob_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='kitob_narxi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
