# Generated by Django 6.0.1 on 2026-01-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0009_alter_kitob_kitob_narxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='kitoblar/static/files'),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kitoblar/static/images'),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='kitob_narxi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
