# Generated by Django 6.0.1 on 2026-01-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0008_alter_kitob_image'),
        ('kitoblar', '0011_kitob_is_favorite'),
    ]

    operations = [
    ]
