# Generated by Django 6.0.1 on 2026-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0012_merge_0008_alter_kitob_image_0011_kitob_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kitoblar/static/images'),
        ),
    ]
