# Generated by Django 6.0.1 on 2026-03-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0007_kitob_narxi'),
        ('kitoblar', '0013_alter_kitob_image'),
    ]

    operations = [
    ]
