# Generated by Django 6.0.1 on 2026-03-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0014_merge_0007_kitob_narxi_0013_alter_kitob_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitob',
            name='narxi',
        ),
    ]
